name: R Markdown Rendering

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'knitr', 'yaml', 'tinytex'), repos = 'https://cloud.r-project.org/')"

      - name: Render R Markdown files
        run: |
          Rscript -e "rmarkdown::render_site()"

      - name: Upload rendered site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site/
