name: Render R Markdown

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensures that the full history is fetched to avoid issues with some workflows

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x' # Specify the R version you want to use

    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('rmarkdown', 'knitr', 'yaml', 'tinytex'), repos = 'https://cloud.r-project.org/')"
        Rscript -e "tinytex::install_tinytex()" # Optional: Only if you use LaTeX for rendering

    - name: Install Pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Render R Markdown
      run: |
        Rscript -e "rmarkdown::render_site()"
